---

#__docker_repo_url: "deb https://download.docker.com/linux/{{ ansible_distribution | lower}} {{ ansible_distribution_release }} {{ __docker_build }}"
#__docker_repo_key:
#  url: "https://download.docker.com/linux/{{ ansible_distribution | lower}}/gpg"
#  id:
#__docker_package: docker-ce
#__docker_version: 17.03.0~ce-0~{{ ansible_distribution | lower}}-{{ ansible_distribution_release }}
#__docker_build: stable
__docker_pre_packages:
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - curl
  - software-properties-common
  - python-dev
  - python-setuptools

# Old versions
##############
__docker_repo_url: "deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower}}-{{ ansible_distribution_release }} {{ __docker_build }}"
__docker_build: main
__docker_repo_key:
  url: "hkp://ha.pool.sks-keyservers.net:80"
  id: 58118E89F3A912897C070ADBF76221572C52609D
__docker_package: docker-engine
__docker_version: 1.12.6-0~{{ ansible_distribution | lower}}-{{ ansible_distribution_release }}
__docker_build: main
