---

- name: apt-get update
  raw: apt-get update -qq

- name: Install python 2.7
  raw: apt-get install -yqq python

- name: set python to python2.7
  set_fact:
    ansible_python_interpreter: /usr/bin/python

- name: Install python apt
  command: "apt-get install -y python-apt"

- name: Install dependencies
  apt:
      name={{ item }}
      update_cache=yes
      state=present
  with_items: "{{ __docker_pre_packages }}"

- name: Install pip
  easy_install:
      name=pip

- name: Install docker-py
  pip:
    name=docker-py
    state=present

# use shell module to be compatible with older OS versions
- name: Add docker apt repo key
  shell: "curl -fsSL {{ __docker_repo_key.url }} | sudo apt-key add -"
  when: __docker_package == "docker-ce"

- name: Add docker apt repo key for older versions
  apt_key:
      keyserver={{ __docker_repo_key.url }}
      state=present
      id={{ __docker_repo_key.id }}
  when:  __docker_package == "docker-engine"

- name: Add docker apt repo
  apt_repository:
    repo='{{ __docker_repo_url }}'
    state=present

- name: Install Docker package
  apt:
    name="{{ __docker_package }}={{ __docker_version }}"
    update_cache=yes
